### ISSUE TITLE
Currently referring old repo names

### ISSUE THREAD

**Issue by rhoslynroebuck** [IRL2/nanover-docs#133]
The following git repos have changed names, and we need to make sure we update them across the docs:

- [x] nanover-server-py (previously nanover-protocol) - Fixed #132 
- [x] nanover-imd-vr (previously nanover-imd) - Fixed #127 
- [x] nanover-server-rs (previously nanover-rs) - Fixed #132

**Comment by rhoslynroebuck** [comment]
Closed by the PRs specified above.
